export const SET_PLACES = 'SET_PLACES';
export const SELECT_PLACE = 'SELECT_PLACE';
export const SET_PLACE_TYPE_FILTER = 'SET_PLACE_TYPE_FILTER';
export const SET_USER_GEOLOCATION = 'SET_USER_GEOLOCATION';
